import { Platform, Alert } from 'react-native';
import * as FileSystem from 'expo-file-system';
import * as Sharing from 'expo-sharing';
import ApiService from './api';

/**
 * Fetches a PDF generated by the backend (auth token attached) and hands it to
 * the user: a browser download on web, the share sheet on native. Backend PDF
 * endpoints stream `application/pdf` with a `Content-Disposition` header, the
 * same way the loan report does.
 *
 * @param {string} path   API path relative to the base, e.g.
 *                         `/chamas/123/transactions/report?scope=personal`
 * @param {string} fileName  suggested file name (sanitised)
 * @param {string} dialogTitle  native share-sheet title
 */
export async function downloadBackendPdf({ path, fileName, dialogTitle = 'Download PDF' }) {
  const base = String(ApiService.getApiBaseUrl?.() || '').replace(/\/$/, '');
  const token = await ApiService.getAuthToken();
  const url = `${base}${path}`;
  const safeName = String(fileName || 'document.pdf').replace(/[^\w.\-]+/g, '_');

  if (Platform.OS === 'web') {
    const res = await fetch(url, { headers: { Authorization: `Bearer ${token}` } });
    if (!res.ok) {
      let msg = `Download failed (${res.status})`;
      try {
        const j = await res.json();
        if (j?.error) msg = j.error;
      } catch (_) {}
      throw new Error(msg);
    }
    const blob = await res.blob();
    const href = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = href;
    a.download = safeName;
    document.body.appendChild(a);
    a.click();
    a.remove();
    setTimeout(() => URL.revokeObjectURL(href), 4000);
    return { success: true, fileName: safeName };
  }

  if (!FileSystem?.cacheDirectory) {
    throw new Error('Download is not available on this device');
  }

  const dest = `${FileSystem.cacheDirectory}${safeName}`;
  const { uri, status } = await FileSystem.downloadAsync(url, dest, {
    headers: { Authorization: `Bearer ${token}` },
  });
  if (status >= 400) throw new Error(`Download failed (${status})`);

  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, {
      mimeType: 'application/pdf',
      dialogTitle,
      UTI: 'com.adobe.pdf',
    });
  } else {
    Alert.alert('Saved', `Saved to:\n${uri}`);
  }
  return { success: true, fileName: safeName, uri };
}

/** Convenience: download the backend PDF receipt for a single transaction. */
export async function downloadTransactionReceiptPdf(transactionId) {
  const shortId = String(transactionId || '').substring(0, 8).toUpperCase();
  return downloadBackendPdf({
    path: `/receipts/transactions/${encodeURIComponent(transactionId)}/download?format=pdf`,
    fileName: `VaultKe_Receipt_${shortId}_${new Date().toISOString().split('T')[0]}.pdf`,
    dialogTitle: 'Transaction receipt',
  });
}
