package api

import (
	"fmt"
	"net/http"
	"strconv"
	"strings"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/jung-kurt/gofpdf"
)

// Table-based PDF statements, generated server-side with gofpdf in the same
// visual language as the loan report (header band, section rules, zebra tables,
// standard footer). These replace the client-side HTML-to-print receipts.

// newStatementPDF returns an A4 portrait document carrying the standard VaultKe
// header band and footer.
func newStatementPDF(orgName, docTitle, ref string) (*gofpdf.Fpdf, time.Time) {
	pdf := gofpdf.New(gofpdf.OrientationPortrait, "mm", "A4", "")
	pdf.SetMargins(16, 18, 16)
	pdf.SetAutoPageBreak(true, 22)
	genAt := time.Now()

	pdf.SetFooterFunc(func() {
		pdf.SetY(-15)
		pdf.SetDrawColor(rpHair[0], rpHair[1], rpHair[2])
		pdf.SetLineWidth(0.2)
		pdf.Line(16, pdf.GetY(), 194, pdf.GetY())
		pdf.Ln(2)
		pdf.SetFont("Helvetica", "", 7)
		pdf.SetTextColor(rpMuted[0], rpMuted[1], rpMuted[2])
		left := fmt.Sprintf("(c) %d %s. Generated by the %s platform on behalf of %s.",
			genAt.Year(), loanReportAppName, loanReportAppName, sanitize(orgName))
		pdf.CellFormat(150, 4, left, "", 0, "L", false, 0, "")
		pdf.CellFormat(28, 4, fmt.Sprintf("Page %d of {nb}", pdf.PageNo()), "", 0, "R", false, 0, "")
	})
	pdf.AliasNbPages("{nb}")
	pdf.AddPage()

	pdf.SetFillColor(rpBand[0], rpBand[1], rpBand[2])
	pdf.Rect(0, 0, 210, 30, "F")
	pdf.SetXY(16, 7)
	pdf.SetFont("Helvetica", "B", 16)
	pdf.SetTextColor(255, 255, 255)
	pdf.CellFormat(120, 8, sanitize(orgName), "", 2, "L", false, 0, "")
	pdf.SetFont("Helvetica", "", 9)
	pdf.SetTextColor(190, 200, 214)
	pdf.CellFormat(120, 5, docTitle, "", 2, "L", false, 0, "")
	pdf.SetXY(120, 9)
	pdf.SetFont("Helvetica", "", 8)
	pdf.CellFormat(74, 4, "Generated "+genAt.Format("2 Jan 2006, 15:04"), "", 2, "R", false, 0, "")
	if strings.TrimSpace(ref) != "" {
		pdf.CellFormat(74, 4, "Ref "+ref, "", 2, "R", false, 0, "")
	}

	pdf.SetY(38)
	pdf.SetTextColor(rpInk[0], rpInk[1], rpInk[2])
	return pdf, genAt
}

func statementDisclaimer(pdf *gofpdf.Fpdf, orgName string, genAt time.Time) {
	pdf.Ln(7)
	pdf.SetFont("Helvetica", "I", 7.5)
	pdf.SetTextColor(rpMuted[0], rpMuted[1], rpMuted[2])
	pdf.MultiCell(0, 4,
		fmt.Sprintf("This statement is issued by %s and reflects the records held as at %s. It is a computer-generated document and does not require a signature. \"%s\" and the %s wordmark are the property of the %s platform.",
			sanitize(orgName), genAt.Format("2 Jan 2006 15:04 MST"), loanReportAppName, loanReportAppName, loanReportAppName),
		"", "L", false)
	pdf.SetTextColor(rpInk[0], rpInk[1], rpInk[2])
}

func writeStatementPDF(c *gin.Context, pdf *gofpdf.Fpdf, filename string) {
	var buf strings.Builder
	if err := pdf.Output(strWriter{&buf}); err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"success": false, "error": "Failed to render statement"})
		return
	}
	c.Header("Content-Disposition", fmt.Sprintf(`attachment; filename="%s"`, filename))
	c.Data(http.StatusOK, "application/pdf", []byte(buf.String()))
}

func safeFilePart(s string) string {
	var b strings.Builder
	for _, r := range s {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '-' {
			b.WriteRune(r)
		} else {
			b.WriteRune('-')
		}
	}
	out := strings.Trim(b.String(), "-")
	if out == "" {
		out = "vaultke"
	}
	return out
}

/* ------------------------------------------------------------------ *
 *  Subscription payments statement
 * ------------------------------------------------------------------ */

// DownloadChamaSubscriptionReport — GET /chamas/:id/subscription-payments/report
func DownloadChamaSubscriptionReport(c *gin.Context) {
	chamaID, ok := requireParam(c, "id", "Chama ID is required")
	if !ok {
		return
	}
	userID := c.GetString("userID")
	db := dbFromContext(c)
	if db == nil {
		return
	}

	var isMember bool
	if err := db.QueryRow(
		"SELECT EXISTS(SELECT 1 FROM chama_members WHERE chama_id = $1 AND user_id = $2 AND COALESCE(is_active, true))",
		chamaID, userID,
	).Scan(&isMember); err != nil || !isMember {
		c.JSON(http.StatusForbidden, gin.H{"success": false, "error": "You are not a member of this chama"})
		return
	}

	var chamaName string
	_ = db.QueryRow("SELECT COALESCE(name,'') FROM chamas WHERE id = $1", chamaID).Scan(&chamaName)
	if chamaName == "" {
		chamaName = "Chama"
	}

	rows, err := db.Query(`
		SELECT COALESCE(month_year,''), due_date, paid_at, COALESCE(payment_method,''),
		       COALESCE(amount,0), COALESCE(status,''), COALESCE(transaction_id,'')
		FROM subscription_payments
		WHERE chama_id = $1
		ORDER BY due_date
	`, chamaID)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"success": false, "error": "Failed to read subscription payments"})
		return
	}
	defer rows.Close()

	type subRec struct {
		month, method, status, txn string
		due                        time.Time
		paid                       *time.Time
		amount                     float64
	}
	var recs []subRec
	var totalBilled, totalPaid float64
	for rows.Next() {
		var r subRec
		if rows.Scan(&r.month, &r.due, &r.paid, &r.method, &r.amount, &r.status, &r.txn) != nil {
			continue
		}
		recs = append(recs, r)
		totalBilled += r.amount
		if strings.EqualFold(r.status, "paid") || r.paid != nil {
			totalPaid += r.amount
		}
	}

	pdf, genAt := newStatementPDF(chamaName, "Subscription Payments Statement", "")

	pdf.SetFont("Helvetica", "B", 13)
	pdf.CellFormat(120, 8, "Subscriptions", "", 0, "L", false, 0, "")
	pdf.Ln(11)

	sectionTitle(pdf, "Summary")
	outstanding := totalBilled - totalPaid
	if outstanding < 0 {
		outstanding = 0
	}
	kvGrid(pdf, [][2]string{
		{"Total billed", money(totalBilled)},
		{"Total paid", money(totalPaid)},
		{"Outstanding", money(outstanding)},
		{"Records", fmt.Sprintf("%d", len(recs))},
	})
	pdf.Ln(3)

	sectionTitle(pdf, "Payments")
	if len(recs) == 0 {
		emptyLine(pdf, "No subscription payments recorded for this chama.")
	} else {
		w := []float64{26, 28, 28, 32, 34, 30}
		tableHeader(pdf, []string{"Month", "Due", "Paid on", "Method", "Amount", "Status"}, w)
		for i, r := range recs {
			paidOn := "—"
			if r.paid != nil && !r.paid.IsZero() {
				paidOn = r.paid.Format("2 Jan 2006")
			}
			tableRow(pdf, []string{
				orDash(r.month),
				r.due.Format("2 Jan 2006"),
				paidOn,
				title(orDash(r.method)),
				money(r.amount),
				title(orDash(r.status)),
			}, w, i%2 == 1)
		}
	}

	statementDisclaimer(pdf, chamaName, genAt)
	writeStatementPDF(c, pdf, fmt.Sprintf("subscription-statement-%s.pdf", safeFilePart(chamaID)))
}

/* ------------------------------------------------------------------ *
 *  Chama transactions statement
 * ------------------------------------------------------------------ */

var stmtCreditTypes = map[string]bool{
	"contribution": true, "deposit": true, "welfare_contribution": true,
	"loan_payment": true, "loan_repayment": true, "subscription": true,
	"service_fee": true, "share_purchase": true, "shares": true, "merry-go-round": true,
}

// DownloadChamaTransactionsReport — GET /chamas/:id/transactions/report?scope=personal|group|member&memberId=&limit=
func DownloadChamaTransactionsReport(c *gin.Context) {
	chamaID, ok := requireParam(c, "id", "Chama ID is required")
	if !ok {
		return
	}
	userID := c.GetString("userID")
	db := dbFromContext(c)
	if db == nil {
		return
	}

	var role string
	if err := db.QueryRow(
		"SELECT lower(COALESCE(role,'')) FROM chama_members WHERE chama_id = $1 AND user_id = $2 AND COALESCE(is_active, true)",
		chamaID, userID,
	).Scan(&role); err != nil {
		c.JSON(http.StatusForbidden, gin.H{"success": false, "error": "You are not a member of this chama"})
		return
	}
	isOfficer := role == "chairperson" || role == "treasurer" || role == "secretary" || role == "admin"

	scope := strings.ToLower(c.DefaultQuery("scope", "personal"))
	memberID := c.Query("memberId")
	if (scope == "group" || scope == "all" || scope == "member") && !isOfficer {
		c.JSON(http.StatusForbidden, gin.H{"success": false, "error": "Only the chairperson, treasurer or secretary can export group records"})
		return
	}

	limit := 500
	if v, err := strconv.Atoi(c.Query("limit")); err == nil && v > 0 {
		limit = v
	}
	if limit > 3000 {
		limit = 3000
	}

	var chamaName string
	_ = db.QueryRow("SELECT COALESCE(name,'') FROM chamas WHERE id = $1", chamaID).Scan(&chamaName)
	if chamaName == "" {
		chamaName = "Chama"
	}

	q := `
		SELECT t.created_at, COALESCE(t.type,''), COALESCE(t.description,''),
		       COALESCE(t.amount,0), COALESCE(t.status,''), COALESCE(t.reference,''),
		       TRIM(COALESCE(u.first_name,'') || ' ' || COALESCE(u.last_name,''))
		FROM transactions t
		LEFT JOIN users u ON u.id = t.initiated_by
		WHERE t.chama_id = $1`
	args := []interface{}{chamaID}
	subject := "Group statement"
	switch scope {
	case "personal", "":
		q += ` AND (t.initiated_by = $2 OR t.recipient_id = $2)`
		args = append(args, userID)
		subject = "Personal statement"
	case "member":
		if memberID == "" {
			c.JSON(http.StatusBadRequest, gin.H{"success": false, "error": "memberId is required for a member statement"})
			return
		}
		q += ` AND (t.initiated_by = $2 OR t.recipient_id = $2)`
		args = append(args, memberID)
		var mn string
		_ = db.QueryRow("SELECT TRIM(COALESCE(first_name,'') || ' ' || COALESCE(last_name,'')) FROM users WHERE id = $1", memberID).Scan(&mn)
		if strings.TrimSpace(mn) != "" {
			subject = "Statement for " + strings.TrimSpace(mn)
		}
	}
	q += fmt.Sprintf(` ORDER BY t.created_at DESC LIMIT %d`, limit)

	rows, err := db.Query(q, args...)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"success": false, "error": "Failed to read transactions"})
		return
	}
	defer rows.Close()

	type txRec struct {
		at                            time.Time
		kind, desc, status, ref, name string
		amount                        float64
	}
	var recs []txRec
	var credit, debit float64
	for rows.Next() {
		var r txRec
		if rows.Scan(&r.at, &r.kind, &r.desc, &r.amount, &r.status, &r.ref, &r.name) != nil {
			continue
		}
		recs = append(recs, r)
		if stmtCreditTypes[strings.ToLower(r.kind)] {
			credit += r.amount
		} else {
			debit += r.amount
		}
	}

	pdf, genAt := newStatementPDF(chamaName, "Transactions Statement", "")

	pdf.SetFont("Helvetica", "B", 13)
	pdf.CellFormat(120, 8, subject, "", 0, "L", false, 0, "")
	pdf.Ln(11)

	sectionTitle(pdf, "Summary")
	kvGrid(pdf, [][2]string{
		{"Inflows", money(credit)},
		{"Outflows", money(debit)},
		{"Net", money(credit - debit)},
		{"Transactions", fmt.Sprintf("%d", len(recs))},
		{"Period end", genAt.Format("2 Jan 2006")},
		{"", ""},
	})
	pdf.Ln(3)

	sectionTitle(pdf, "Transactions")
	if len(recs) == 0 {
		emptyLine(pdf, "No transactions found for the selected scope.")
	} else {
		w := []float64{24, 24, 50, 30, 28, 22}
		tableHeader(pdf, []string{"Date", "Type", "Description", "By", "Amount", "Status"}, w)
		for i, r := range recs {
			desc := r.desc
			if strings.TrimSpace(desc) == "" {
				desc = orDash(r.ref)
			}
			tableRow(pdf, []string{
				r.at.Format("2 Jan 06"),
				title(orDash(r.kind)),
				desc,
				orDash(r.name),
				money(r.amount),
				title(orDash(r.status)),
			}, w, i%2 == 1)
		}
	}

	statementDisclaimer(pdf, chamaName, genAt)
	writeStatementPDF(c, pdf, fmt.Sprintf("transactions-statement-%s-%s.pdf", safeFilePart(chamaID), scope))
}
