/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppMenu: typeof import('./src/components/AppMenu/index.vue')['default']
    ApprovalsSnippet: typeof import('./src/components/ApprovalsSnippet.vue')['default']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BCard: typeof import('bootstrap-vue-next')['BCard']
    BCol: typeof import('bootstrap-vue-next')['BCol']
    BForm: typeof import('bootstrap-vue-next')['BForm']
    BFormCheckbox: typeof import('bootstrap-vue-next')['BFormCheckbox']
    BFormGroup: typeof import('bootstrap-vue-next')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BRow: typeof import('bootstrap-vue-next')['BRow']
    ChartJs: typeof import('./src/components/ChartJs.vue')['default']
    CustomerDocumentsComponent: typeof import('./src/components/CustomerDocumentsComponent.vue')['default']
    DropDown: typeof import('./src/components/DropDown.vue')['default']
    FlatPicker: typeof import('./src/components/FlatPicker.vue')['default']
    Gallery: typeof import('./src/components/Gallery.vue')['default']
    InputMask: typeof import('./src/components/InputMask.vue')['default']
    JsVectorMap: typeof import('./src/components/JsVectorMap.vue')['default']
    JustGage: typeof import('./src/components/JustGage.vue')['default']
    LogoBox: typeof import('./src/components/LogoBox.vue')['default']
    MenuItem: typeof import('./src/components/AppMenu/MenuItem.vue')['default']
    MenuItemLink: typeof import('./src/components/AppMenu/MenuItemLink.vue')['default']
    MenuItemWithChildren: typeof import('./src/components/AppMenu/MenuItemWithChildren.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UIComponentCard: typeof import('./src/components/UIComponentCard.vue')['default']
  }
}
