import { StyleSheet } from 'react-native';
import { spacing, typography, borderRadius, shadows } from '../../../utils/theme';

const styles = StyleSheet.create({
  container: { flex: 1 },
  scrollView: { flex: 1 },
  content: { padding: spacing.sm },
  requestCard: { marginBottom: spacing.md },
  requestHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: spacing.md },
  requestInfo: { flex: 1, gap: spacing.sm },
  categoryBadge: { flexDirection: 'row', alignItems: 'center', gap: spacing.xs },
  categoryText: { fontSize: typography.fontSize.sm, fontWeight: typography.fontWeight.medium },
  urgencyBadge: { paddingHorizontal: spacing.sm, paddingVertical: spacing.xs, borderRadius: borderRadius.sm, alignSelf: 'flex-start' },
  urgencyText: { fontSize: typography.fontSize.xs, fontWeight: typography.fontWeight.medium },
  statusBadge: { paddingHorizontal: spacing.sm, paddingVertical: spacing.xs, borderRadius: borderRadius.sm },
  statusText: { fontSize: typography.fontSize.xs, fontWeight: typography.fontWeight.bold },
  requestTitle: { fontSize: typography.fontSize.lg, fontWeight: typography.fontWeight.semibold, marginBottom: spacing.sm },
  requestAmount: { fontSize: typography.fontSize.base, fontWeight: typography.fontWeight.medium },
  requestDescription: { fontSize: typography.fontSize.base, lineHeight: 20, marginBottom: spacing.md },
  requestDetails: { gap: spacing.sm, marginBottom: spacing.md },
  amountContainer: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  amountLabel: { fontSize: typography.fontSize.sm },
  amountValue: { fontSize: typography.fontSize.lg, fontWeight: typography.fontWeight.bold },
  requesterInfo: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  requesterLabel: { fontSize: typography.fontSize.sm },
  requesterName: { fontSize: typography.fontSize.base, fontWeight: typography.fontWeight.medium },
  beneficiaryInfo: { marginTop: spacing.sm },
  beneficiaryLabel: { fontSize: typography.fontSize.sm, marginBottom: spacing.xs },
  beneficiaryName: { fontSize: typography.fontSize.base, fontWeight: typography.fontWeight.medium },
  votingSection: { borderTopWidth: 1, borderTopColor: 'rgba(255, 255, 255, 0.1)', paddingTop: spacing.md },
  votingTitle: { fontSize: typography.fontSize.base, fontWeight: typography.fontWeight.semibold, marginBottom: spacing.sm },
  votingStats: { marginBottom: spacing.md },
  votingButtons: { flexDirection: 'row', gap: spacing.md },
  voteButton: { flex: 1 },
  voteStatItem: { flexDirection: 'row', alignItems: 'center', marginRight: spacing.md },
  voteStatText: { fontSize: typography.fontSize.sm, fontWeight: typography.fontWeight.medium, marginLeft: spacing.xs },
  userVoteStatus: { flexDirection: 'row', alignItems: 'center', paddingVertical: spacing.sm, paddingHorizontal: spacing.md, borderRadius: borderRadius.sm, marginTop: spacing.sm },
  contributionSection: { borderTopWidth: 1, borderTopColor: '#E5E7EB', paddingTop: spacing.md, marginTop: spacing.md },
  contributionTitle: { fontSize: typography.fontSize.base, fontWeight: typography.fontWeight.semibold, marginBottom: spacing.xs },
  contributionSubtitle: { fontSize: typography.fontSize.sm, lineHeight: 18, marginBottom: spacing.md },
  contributeButton: { alignSelf: 'stretch' },
  contributionProgress: { marginVertical: spacing.md, padding: spacing.md, backgroundColor: 'rgba(59, 130, 246, 0.05)', borderRadius: borderRadius.md },
  progressHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: spacing.sm },
  progressLabel: { fontSize: typography.fontSize.sm, fontWeight: typography.fontWeight.medium },
  progressAmount: { fontSize: typography.fontSize.sm, fontWeight: typography.fontWeight.semibold },
  progressBar: { height: 8, borderRadius: 4, marginBottom: spacing.sm },
  progressFill: { height: '100%', borderRadius: 4 },
  progressDetails: { marginTop: spacing.sm },
  progressDetailRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  progressDetailItem: { flex: 1, alignItems: 'center' },
  progressDetailLabel: { fontSize: typography.fontSize.xs, marginBottom: spacing.xs / 2 },
  progressDetailValue: { fontSize: typography.fontSize.sm, fontWeight: typography.fontWeight.semibold },
  progressPercentage: { fontSize: typography.fontSize.xs, textAlign: 'center' },
  requestActions: { flexDirection: 'row', gap: spacing.md },
  actionButton: { flex: 1 },
  centerContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', paddingHorizontal: spacing.xl },
  emptyTitle: { fontSize: typography.fontSize.lg, fontWeight: typography.fontWeight.semibold, marginTop: spacing.md, marginBottom: spacing.sm, textAlign: 'center' },
  emptySubtitle: { fontSize: typography.fontSize.base, textAlign: 'center', paddingHorizontal: spacing.xl },
  backButton: { paddingHorizontal: spacing.lg, paddingVertical: spacing.md, borderRadius: borderRadius.md },
  backButtonText: { fontSize: typography.fontSize.base, fontWeight: typography.fontWeight.semibold },
  tabContainer: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: 'rgba(0, 0, 0, 0.1)' },
  tab: { flex: 1, paddingVertical: spacing.md, alignItems: 'center', borderBottomWidth: 2, borderBottomColor: 'transparent' },
  activeTab: { borderBottomWidth: 2 },
  tabText: { fontSize: typography.fontSize.base, fontWeight: typography.fontWeight.medium },
  emptyState: { alignItems: 'center', justifyContent: 'center', paddingVertical: spacing.xl * 2 },
  fab: { width: 56, height: 56, borderRadius: 28, alignItems: 'center', justifyContent: 'center', ...shadows.lg },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0, 0, 0, 0.5)', justifyContent: 'flex-end' },
  modalContent: { borderTopLeftRadius: borderRadius.xl, borderTopRightRadius: borderRadius.xl, paddingHorizontal: spacing.md, paddingBottom: spacing.xl, maxHeight: '80%', maxWidth: 500, alignSelf: 'center', width: '95%' },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: spacing.lg, borderBottomWidth: 1, borderBottomColor: 'rgba(255, 255, 255, 0.1)', marginBottom: spacing.lg },
  modalTitle: { fontSize: typography.fontSize.lg, fontWeight: typography.fontWeight.semibold },
  modalBody: { gap: spacing.md },
  inputContainer: { marginBottom: spacing.md },
  inputError: {},
  sectionError: {},
  sectionTitle: { fontSize: typography.fontSize.base, fontWeight: typography.fontWeight.semibold, marginTop: spacing.md, marginBottom: spacing.sm },
  categoryGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md, marginBottom: spacing.md },
  categoryGridItem: { width: '48%', flexDirection: 'column', alignItems: 'center', paddingVertical: spacing.sm, paddingHorizontal: spacing.xs, borderRadius: borderRadius.md, borderWidth: 1, gap: spacing.xs },
  categoryIconCircle: { width: 36, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center' },
  categoryGridText: { fontSize: typography.fontSize.xs, fontWeight: typography.fontWeight.medium, textAlign: 'center', lineHeight: typography.fontSize.xs * 1.3 },
  urgencyGrid: { flexDirection: 'row', gap: spacing.md, marginBottom: spacing.lg },
  urgencyGridItem: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: spacing.sm, paddingHorizontal: spacing.sm, borderRadius: borderRadius.md, borderWidth: 1, gap: spacing.xs },
  urgencyDot: { width: 6, height: 6, borderRadius: 3 },
  urgencyGridText: { fontSize: typography.fontSize.xs, fontWeight: typography.fontWeight.semibold, textAlign: 'center' },
  beneficiarySection: { flexDirection: 'row', gap: spacing.sm, marginBottom: spacing.md },
  beneficiaryOption: { flex: 1, flexDirection: 'row', alignItems: 'center', paddingHorizontal: spacing.md, paddingVertical: spacing.md, borderRadius: borderRadius.md, borderWidth: 1, gap: spacing.sm },
  beneficiaryOptionText: { fontSize: typography.fontSize.sm, fontWeight: typography.fontWeight.medium },
  selectedBeneficiary: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: spacing.sm, paddingHorizontal: spacing.sm, backgroundColor: 'rgba(255, 255, 255, 0.1)', borderRadius: borderRadius.sm },
  beneficiaryInfo: { flexDirection: 'row', alignItems: 'center', flex: 1, gap: spacing.sm },
  beneficiaryAvatar: { width: 32, height: 32, borderRadius: 16, backgroundColor: 'rgba(59, 130, 246, 0.3)', alignItems: 'center', justifyContent: 'center' },
  beneficiaryAvatarText: { fontSize: typography.fontSize.sm, fontWeight: typography.fontWeight.bold },
  beneficiaryDetails: { flex: 1 },
  beneficiaryName: { fontSize: typography.fontSize.base, fontWeight: typography.fontWeight.semibold, marginBottom: spacing.xs },
  beneficiaryRole: { fontSize: typography.fontSize.xs, textTransform: 'capitalize' },
  removeBeneficiaryButton: { padding: spacing.xs },
  addBeneficiaryButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: spacing.md, borderRadius: borderRadius.md, borderWidth: 1, gap: spacing.sm },
  addBeneficiaryText: { fontSize: typography.fontSize.sm, fontWeight: typography.fontWeight.medium },
  searchContainer: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: spacing.md, paddingVertical: spacing.sm, backgroundColor: 'rgba(255, 255, 255, 0.05)', borderRadius: borderRadius.md, marginBottom: spacing.md, gap: spacing.sm },
  searchInput: { flex: 1, fontSize: typography.fontSize.base, paddingVertical: spacing.sm },
  membersList: { maxHeight: 400 },
  loadingContainer: { alignItems: 'center', justifyContent: 'center', paddingVertical: spacing.xl, gap: spacing.md },
  loadingText: { fontSize: typography.fontSize.base },
  memberOption: { flexDirection: 'row', alignItems: 'center', paddingVertical: spacing.md, paddingHorizontal: spacing.md, borderRadius: borderRadius.md, marginBottom: spacing.xs, gap: spacing.md },
  memberAvatar: { width: 40, height: 40, borderRadius: 20, backgroundColor: 'rgba(59, 130, 246, 0.2)', alignItems: 'center', justifyContent: 'center' },
  memberAvatarText: { fontSize: typography.fontSize.sm, fontWeight: typography.fontWeight.bold },
  memberInfo: { flex: 1 },
  memberDetails: { flex: 1 },
  memberName: { fontSize: typography.fontSize.base, fontWeight: typography.fontWeight.semibold, marginBottom: spacing.xs },
  memberEmail: { fontSize: typography.fontSize.sm, marginBottom: spacing.xs },
  memberRole: { fontSize: typography.fontSize.xs, textTransform: 'capitalize' },
  emptyMembers: { alignItems: 'center', justifyContent: 'center', paddingVertical: spacing.xl * 2, gap: spacing.md },
  emptyMembersText: { fontSize: typography.fontSize.base, fontWeight: typography.fontWeight.medium },
  emptyMembersSubtext: { fontSize: typography.fontSize.sm },
  errorText: { fontSize: typography.fontSize.sm, marginTop: spacing.xs, marginLeft: spacing.sm },
  errorSummary: { backgroundColor: 'rgba(239, 68, 68, 0.1)', borderColor: '#EF4444', borderWidth: 1, borderRadius: borderRadius.md, padding: spacing.md, marginVertical: spacing.md },
  errorSummaryHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: spacing.sm, gap: spacing.sm },
  errorSummaryTitle: { fontSize: typography.fontSize.base, fontWeight: typography.fontWeight.semibold },
  errorSummaryItem: { fontSize: typography.fontSize.sm, marginLeft: spacing.md, marginBottom: spacing.xs },
  submitButtonDisabled: { backgroundColor: '#9CA3AF', opacity: 0.6 },
  submitButtonTextDisabled: { color: '#6B7280' },
  categorySection: { marginBottom: spacing.md },
  urgencySection: { marginBottom: spacing.lg },
  viewModalOverlay: { flex: 1, backgroundColor: 'rgba(0, 0, 0, 0.5)', justifyContent: 'center', alignItems: 'center', padding: spacing.lg },
  viewModalContent: { width: '95%', maxWidth: 400, maxHeight: '80%', borderRadius: borderRadius.lg, ...shadows.lg },
  viewModalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: spacing.lg, borderBottomWidth: 1, borderBottomColor: 'rgba(0, 0, 0, 0.1)' },
  viewModalTitle: { fontSize: typography.fontSize.lg, fontWeight: typography.fontWeight.semibold, flex: 1, marginRight: spacing.md },
  viewModalCloseButton: { padding: spacing.xs },
  viewModalBody: { padding: spacing.lg },
  viewModalItem: { gap: spacing.md },
  viewModalSection: { marginBottom: spacing.md },
  viewModalSectionTitle: { fontSize: typography.fontSize.base, fontWeight: typography.fontWeight.semibold, marginBottom: spacing.xs },
  viewModalSectionContent: { fontSize: typography.fontSize.base, lineHeight: 22 },
  viewModalRow: { flexDirection: 'row', marginBottom: spacing.md },
  viewModalHalf: { flex: 1, marginRight: spacing.sm },
  actionModalOverlay: { flex: 1, backgroundColor: 'rgba(0, 0, 0, 0.5)', justifyContent: 'center', alignItems: 'center', padding: spacing.xl },
  actionModalContent: { width: '90%', maxWidth: 320, maxHeight: '50%', borderRadius: borderRadius.lg, paddingBottom: spacing.md },
  actionModalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: spacing.sm, borderBottomWidth: 1, borderBottomColor: 'rgba(0, 0, 0, 0.1)' },
  actionModalTitle: { fontSize: typography.fontSize.sm, fontWeight: typography.fontWeight.semibold, flex: 1, marginRight: spacing.sm },
  actionModalCloseButton: { padding: spacing.xs },
  actionModalBody: { flex: 1, padding: spacing.sm },
  actionModalButton: { flexDirection: 'row', alignItems: 'center', padding: spacing.sm, borderRadius: borderRadius.sm, marginBottom: spacing.sm, ...shadows.sm },
  actionModalButtonText: { marginLeft: spacing.md, flex: 1 },
  actionModalButtonTitle: { fontSize: typography.fontSize.sm, fontWeight: typography.fontWeight.medium, marginBottom: spacing.xs / 4 },
  actionModalButtonSubtitle: { fontSize: typography.fontSize.xs },
  pagination: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', paddingVertical: spacing.md, paddingHorizontal: spacing.lg, gap: spacing.sm },
  pageButton: { width: 36, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center', borderWidth: 1 },
  pageButtonDisabled: { opacity: 0.5 },
  pageText: { fontSize: typography.fontSize.sm, fontWeight: typography.fontWeight.medium, marginHorizontal: spacing.md },
});

export default styles;
